apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml

namespace: app-consult

images:
- name: appconsult
  newName: nandocloud/app-consult
  newTag: 1dbd566075dccc96b3908f5e8c312efd0d0e1cfa
- name: react-application
  newName: appconsult
  newTag: latest
